name: Deploy test.html

on:
  push:
    branches:
      - main # Trigger on changes to the main branch
  workflow_dispatch:
    inputs:
      name:
        type: multi-choice
        description: select packages
        options:
          - go-service1
          - go-service2
          - py-service1
        required: true
        multiselect: true

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Check out the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Deploy test.html to S3 bucket
      - name: Deploy test.html to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp ./test.html s3://qoala-ass-1/test.html

      # Step 3: Invalidate CloudFront Cache
      - name: Invalidate CloudFront Cache
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws cloudfront create-invalidation --distribution-id ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }} --paths "/test.html"
